from django.core.exceptions import ValidationError
import re


def validate_time(time):
    pass
